### ISSUE TITLE
Upon trying to open, "This app cannot be opened, please move to trash."

### ISSUE THREAD

**Issue by jonboulier** [eviathan/Pelt#11]
(Can you e-mail me and let me know if this will be updated or if you plan on continuing to work on this? Or if you can help?)

Here's the error message I get from the error report:

Process:               Pelt [11901]
Path:                  /private/var/folders/*/Pelt.app/Contents/MacOS/Pelt
Identifier:            iko.eviathan.Pelt
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Pelt [11901]
User ID:               501

Date/Time:             2018-09-28 00:20:25.938 -0400
OS Version:            Mac OS X 10.13.6 (17G65)
Report Version:        12
Anonymous UUID:        16D375FD-AF5D-5FD1-121B-11B1EB01D23F

Sleep/Wake UUID:       56292161-029F-47CA-A8F9-B68B6D9EEBF9

Time Awake Since Boot: 15000 seconds
Time Since Wake:       6600 seconds

System Integrity Protection: enabled

Notes:                 Translocated Process

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
    __TEXT                 00000001062c5000-00000001062ec000 [  156K] r-x/rwx SM=COW  ! []

Thread 0 Crashed:
0   ???                           	0x000000010ec6f19c _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ffee993aad0
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x000000010ec6f19c  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     0

Binary Images:
       0x1062c5000 -        0x1062ebff7 +??? (0) <E53967AF-A1CE-3A5D-AE4C-0B52CC02D042> (null)
       0x10ec6e000 -        0x10ecb8acf +??? (551.4) <8A72DE9C-A136-3506-AA02-4BA2B82DCAF3> (null)

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 13530
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=752K resident=0K(0%) swapped_out_or_unallocated=752K(100%)
Writable regions: Total=8404K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8404K(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        2 
Stack                             8192K        2 
__DATA                             252K        4 
__LINKEDIT                         296K        3 
__TEXT                             456K        3 
shared memory                        8K        3 
===========                     =======  ======= 
TOTAL                             65.0M       11 

Model: MacBookPro11,3, BootROM MBP112.0146.B00, 4 processors, Intel Core i7, 2.3 GHz, 16 GB, SMC 2.19f12
Graphics: Intel Iris Pro, Intel Iris Pro, Built-In
Graphics: NVIDIA GeForce GT 750M, NVIDIA GeForce GT 750M, PCIe
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x134), Broadcom BCM43xx 1.0 (7.77.37.31.1a9)
Bluetooth: Version 6.0.7f10, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
PCI Card: Focusrite Clarett, Unknown, Thunderbolt@195,0,0
Serial ATA Device: APPLE SSD SM0512F, 500.28 GB
USB Device: USB 3.0 Bus
USB Device: USB3.0 Hub
USB Device: BUP Slim SL
USB Device: BUP Slim Mac SL
USB Device: USB3.0 Hub
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB2.0 Hub
USB Device: Touro Mobile 3.0
USB Device: USB2.0 Hub
USB Device: Hub
USB Device: Hub
USB Device: USB Keyboard
USB Device: Flash Card Reader
USB Device: HL-L2340D series
Thunderbolt Bus: MacBook Pro, Apple Inc., 17.1
Thunderbolt Device: Clarett2Pre, Focusrite, 3, 7.1

**Comment by eviathan** [comment]
@jonboulier Hi there I will try to find some time to replicate and fix this bug. It is probably a build target issue.

**Comment by eviathan** [comment]
@jonboulier this has been fixed you can grab the latest version from the releases section or using the link below.

[Download](https://github.com/eviathan/Pelt/releases/download/1.0.1-alpha.1.5/Pelt.1.0.1-alpha.1.5.zip)

**Comment by jonboulier** [comment]
Unfortunately, I can’t open the application because it “doesn’t work with this version of MacOS,” — I’m on High Sierra.
