### ISSUE TITLE
Mojave Crash

### ISSUE THREAD

**Issue by jaydaniels** [eviathan/Pelt#12]
<img width="1003" alt="screen shot 2018-10-07 at 10 45 40 pm" src="https://user-images.githubusercontent.com/8453581/46591807-ce452f80-ca82-11e8-8bfe-b45bbcc653a0.png">

Process:               Pelt [6996]
Path:                  /private/var/folders/*/Pelt.app/Contents/MacOS/Pelt
Identifier:            iko.eviathan.Pelt
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Pelt [6996]
User ID:               501

Date/Time:             2018-10-07 22:44:46.374 -0500
OS Version:            Mac OS X 10.14 (18A391)
Report Version:        12
Bridge OS Version:     3.0 (14Y667)
Anonymous UUID:        C71807ED-5104-CCF9-D0ED-BFE8C6910139

Sleep/Wake UUID:       E0C2D2C8-34CE-4839-8CAD-B8FA627A46B5

Time Awake Since Boot: 43000 seconds
Time Since Wake:       32000 seconds

System Integrity Protection: enabled

Notes:                 Translocated Process

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
    __TEXT                 0000000102f8f000-0000000102fb6000 [  156K] r-x/rwx SM=COW  

Thread 0 Crashed:
0                                 	0x000000010af12000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ffeecc70b08
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x000000010af12000  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     0

Binary Images:
       0x102f8f000 -        0x102fb5ff7 + (0) <E53967AF-A1CE-3A5D-AE4C-0B52CC02D042> 
       0x10af11000 -        0x10af8f6a7 + (625.13) <D6387150-2FB8-3066-868D-72E1B1C43982> 

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 26172
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1016K resident=0K(0%) swapped_out_or_unallocated=1016K(100%)
Writable regions: Total=8400K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8400K(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        2 
Stack                             8192K        2 
__DATA                             256K        4 
__LINKEDIT                         352K        3 
__TEXT                             664K        3 
shared memory                        8K        3 
===========                     =======  ======= 
TOTAL                             65.2M       11 

Model: MacBookPro14,2, BootROM MBP142.0178.B00, 2 processors, Intel Core i5, 3.1 GHz, 8 GB, SMC 2.44f1
Graphics: Intel Iris Plus Graphics 650, Intel Iris Plus Graphics 650, Built-In
Memory Module: BANK 0/DIMM0, 4 GB, LPDDR3, 2133 MHz, 0x80CE, 0x4B3445364533303445422D45474347202020
Memory Module: BANK 1/DIMM0, 4 GB, LPDDR3, 2133 MHz, 0x80CE, 0x4B3445364533303445422D45474347202020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x171), Broadcom BCM43xx 1.0 (7.77.61.1 AirPortDriverBrcmNIC-1305.2)
Bluetooth: Version 6.0.8f6, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.0 Bus
USB Device: iBridge
USB Device: My Passport 25E3
USB Device: My Passport 25E3
Thunderbolt Bus: MacBook Pro, Apple Inc., 37.1
Thunderbolt Bus: MacBook Pro, Apple Inc., 37.1

**Comment by eviathan** [comment]
@digitalself  Oh sorry no I have recently changed jobs so I have been in a bit of a cufuddelled state adjusting to the changes.

I will look at it now.

**Comment by digitalself** [comment]
@eviathan awesome - do you have a tip jar or something where I can chuck you a few bucks?

**Comment by eviathan** [comment]
@digitalself Thats extremely kind. There was a paypal donation thing I linked to it on the windows version but didnt get around to adding it to the OSX version.

[https://paypal.me/eviathan](url)

**Comment by eviathan** [comment]
@digitalself try this [https://github.com/eviathan/Pelt/releases/tag/1.0.1-alpha.1.4](url)

**Comment by digitalself** [comment]
OK, it opens now, but when I load an existing theme everything stays blank and it doesn't load the theme's settings... any ideas?

**Comment by eviathan** [comment]
@digitalself Can you upload the theme file here and link it to me. They may have changed the schema since I developed this.

I put it to the side because I was trying to nag Ableton for their sketch (vectors) file so I could build the preview part of the application but they didnt get back to me.

**Comment by digitalself** [comment]
here you go man.

[03Dark.ask.zip](https://github.com/eviathan/Pelt/files/2658276/03Dark.ask.zip)

**Comment by eviathan** [comment]
@digitalself Thank you I will debug it now. I should be able to get this sorted quickly but in the mean time If you have access to a windows machine you could check out that one too, its called fuzz and you can find a link to it [here](https://github.com/eviathan/Fuzz)

**Comment by digitalself** [comment]
I removed my bootcamp partition cos I've got too many Kontakt libraries and ran out of space! will see if a mate can help me out. thanks again man.

**Comment by eviathan** [comment]
@digitalself  I can replicate the same behaviour so I can find out whats happening and patch it up now. 

Thank you for the donation I will let you know when its fixed.

**Comment by eviathan** [comment]
@digitalself Well theres the problem!

<img width="413" alt="screenshot 2018-12-07 at 18 05 16" src="https://user-images.githubusercontent.com/26843345/49664746-aeae9100-fa4a-11e8-8f50-747edee0879e.png">

Its working its just when you open the file it thinks that its empty. No idea why that is because this is all handled by apples on file handling frameworks. I will prod it till its fixed but it may not be possible tonight as I have no idea why it has started doing it and will need to research it.

**Comment by digitalself** [comment]
well, the first battle is won, good luck with the rest of the war!

**Comment by eviathan** [comment]
@digitalself 

well that was silly. The library I was using for xml parsing patched breaking changes in a minor version update. Ultimately thats an instant disqualification for trust. I will migrate it over to swifts native xml parsing when I have time. 

Either way. Give that a spin and let me know if you have any other issues.

[Download](https://github.com/eviathan/Pelt/releases/download/1.0.1-alpha.1.5/Pelt.1.0.1-alpha.1.5.zip)


<img width="406" alt="screenshot 2018-12-09 at 12 56 55" src="https://user-images.githubusercontent.com/26843345/49697652-01ef2380-fbb2-11e8-809e-c02cee055cba.png">

**Comment by digitalself** [comment]
that got her going! thanks so much mate!

**Comment by eviathan** [comment]
A pleasure.

**Comment by davidvb** [comment]
Hi there! 
Unfortunately I am still having this exact same crash on each run with 1.0.1-alpha.1.5.
I'm on Mojave 10.14.2 Beta (18C52a)
